#!/bin/sh

NVRAM=${NVRAM:-64}
MEM=${MEM:-256}

cd /iou

# disable IPv6 and set MTU to 9000
for if_eth in `sed -n 's/^ *\(eth[0-9]*\):.*/\1/p' /proc/net/dev`; do
	ifconfig $if_eth down
	sysctl -q -w net.ipv6.conf.$if_eth.disable_ipv6=1
	ifconfig $if_eth mtu 9000 up
done

# update /etc/hosts
if ! fgrep -q -w "gns3vm" /etc/hosts; then
	echo -e '127.0.1.2\tgns3vm' >> /etc/hosts
	echo -e '127.0.0.127\txml.cisco.com' >> /etc/hosts
fi

# create router ID
ID=`echo $ID | grep -o '[0-9-]*$'`
[ -z "$ID" ] && ID=0x`echo $HOSTNAME | md5sum | grep -o '^................'`
ID=$(($ID % 997))
[ $ID -le 0 ] && ID=$(($ID + 997))
nvram_file=`printf "nvram_%05d" $ID`
find nvram_* ! -name $nvram_file | xargs -r rm

# create NETMAP and iouyap.ini
echo -n "" > NETMAP
echo -e "[default]\nbase_port = 49000\nnetmap = NETMAP\n" > iouyap.ini

if_last=0
for if_eth in `sed -n 's/^ *eth\([0-9]*\):.*/\1/p' /proc/net/dev`; do
	if_iou="$(($if_eth / 4))/$(($if_eth % 4))"
	echo "1000:$if_iou $ID:$if_iou" >> NETMAP
	echo -e "[1000:$if_iou]\neth_dev = eth$if_eth\n" >> iouyap.ini
	[ $if_last -lt $if_eth ] && if_last=$if_eth
done
num_eth=$(($if_last / 4 + 1))
num_ser=0
if [ $num_eth -gt 2 ]; then
	num_eth=$(($num_eth - 1))
	num_ser=1
fi

# first run: replace %h by hostname in config files
if [ ! -f $nvram_file ]; then
	[ -f startup-config ] && sed -i "s/%h/$HOSTNAME/g" startup-config
	[ -f private-config ] && sed -i "s/%h/$HOSTNAME/g" private-config
fi

# update NVRAM
if [ -f startup-config ]; then
	[ -f private-config ] && private="private-config" || private=""
	iou_import -c "$NVRAM" $nvram_file startup-config $private
fi

# start IOU
hostname gns3vm
stty intr undef quit undef susp undef
iouyap 1000 > iouyap.log 2>&1 &
exec iou.bin -e $num_eth -s $num_ser -n "$NVRAM" -m "$MEM" $ID
